/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-24_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-30_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-37_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-41_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-47_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-51_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bil1-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud1-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud1-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud1-9_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud2-45_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud2-52_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud2-54_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud2-73_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud2-81_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud2-86_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud3-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bud3-30_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi-2-26_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-16_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-29_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-58_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-61_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-64_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-69_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-71_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-74_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bwi1-78_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-12_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-14_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-16_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Chinko-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/El3-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/El3-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-21_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-23_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-24_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-47_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-59_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-70_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis1-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis2-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis2-50_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gis2-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kab1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kab1-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kab1-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N173-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N173-14_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N181-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N181-14_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N183-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N183-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N186-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N186-9_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N190-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N259-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N259-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N259-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N260-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N260-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N260-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N261-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N261-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/N262-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-26_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-34_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-40_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-44_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-54_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-57_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-77_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP1-86_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP2-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP2-35_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP2-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP2-55_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP2-67_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/NNP3-14_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt1-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt1-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt1-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-14_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-21_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-22_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-24_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-35_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-37_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-38_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Rt2-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga1-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga1-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga1-12_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga1-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga1-22_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga1-34_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga1-9_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-22_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-31_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-41_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-44_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-49_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-53_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-73_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-74_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga2-81_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Uga3-29_exome.addRG.bam
