/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bat1-22_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bat1-39_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bat1-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bat1-48_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Bat1-50_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CMNP1-24_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con1-12_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-38_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-48_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-49_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-50_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-53_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-56_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-57_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con2-80_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Con3-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Dja1-16_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Dja1-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Dja2-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Dja2-27_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Dja2-30_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Dja3-19_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-10-03_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-11-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-13-21_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-14-05_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-22-06_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-25-05_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-28-02_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-34-16_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-34-22_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-36-07_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/GB-37-04_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-18_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-21_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-23_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-27_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-58_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-61_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-66_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-70_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gou1-75_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/LCA-3-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/LCA-3-12_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop2-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop2-16_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop2-34_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop2-35_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop2-77_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop2-80_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop2-82_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop2-88_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop3-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lop3-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-26_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-54_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-55_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-56_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-58_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-63_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-66_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-67_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-71_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Mtc1-72_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/MTC2-24_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/MTC2-31_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/MTC2-33_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/MTC2-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/MTC2-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/MTC2-7_exome.addRG.bam
