/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf1-12_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf1-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf1-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf1-19_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf1-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf2-27_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf2-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf2-43_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf2-46_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf2-68_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf2-73_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf2-74_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Baf2-75_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-30_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-32_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-33_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-36_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-43_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-44_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-57_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-71_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-75_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe1-77_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe2-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe2-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe2-22_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe2-26_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe2-30_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe2-33_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe2-39_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Boe2-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-14_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-36_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-37_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-47_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-63_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-70_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Cnp1-75_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPE1-22_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPE1-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPE1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPN1-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPN1-35_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPN1-63_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPW1-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPW1-16_2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPW1-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPW1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPW1-40_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPW1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/CNPW2-29_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din1-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din1-26_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din1-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din1-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din1-53_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din1-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din2-29_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din2-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din2-38_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din2-43_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din2-79_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din2-83_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din3-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din3-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Din3-9_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo1-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo1-14_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo1-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo1-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo1-60_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo1-66_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo2-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo2-68_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Djo3-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn1-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn1-21_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn1-22_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn1-42_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn2-50_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn2-52_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn2-62_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn2-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn3-24_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn3-43_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn3-53_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn3-54_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn3-68_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fjn3-84_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta1-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta1-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta1-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta2-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-29_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-34_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-35_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-37_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-38_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-40_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-51_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-55_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-80_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-82_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Fouta3-87_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo1-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo1-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo1-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo1-27_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo1-41_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo1-86_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo2-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo2-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo2-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo2-57_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo2-59_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo2-63_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo2-66_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo2-85_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo3-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gbo3-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-32_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-33_2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-43_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-44_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-48_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-51_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-61_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco1-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco2-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco2-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco2-9_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gco4-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep1-21_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep1-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep1-26_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep1-62_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-28_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-30_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-37_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-40_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-41_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-45_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-48_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-52_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-53_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gep2-61_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Gha-01-05_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay1-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay1-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay1-16_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay1-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay1-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay1-23_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay1-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay2-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay2-29_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay2-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay2-32_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay2-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay2-41_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay2-49_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Kay2-54_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib2-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib2-14_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib2-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib2-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib2-28_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib2-48_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib2-62_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib2-66_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Lib3-34_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-47_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-49_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-51_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-52_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-77_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-78_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim1-79_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim2-12_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim2-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim2-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim2-33_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim2-34_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim2-35_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim2-44_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Nim2-58_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-12_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-24_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-25_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-27_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-28_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-39_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-7_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Onp1-9_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-17_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-19_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-3_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-32_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-39_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San1-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-1_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-10_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-16_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-20_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-26_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-49_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-53_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/San2-59_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-27_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-31_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-33_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-56_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-57_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-6_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-77_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-83_2_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob1-84_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Sob2-5_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R1-28_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R1-4_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R2-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R2-15_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R2-18_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R2-30_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R2-43_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R2-52_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R2-80_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai_R2-88_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai-E1-13_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai-E1-8_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai-E2-11_exome.addRG.bam
/home/ucfajos/Scratch/data/phase1and2_exomes/BAM.mapped.on.target/Tai-E2-31_exome.addRG.bam
